language: go
go: 1.14
sudo: false
before_script:
 - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh
cache:
  directories:
    - $GOPATH/pkg/mod
script:
- ./bin/golangci-lint run
- go test -race ./...
