apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelines-app-delivery-backend
  labels:
    app.kubernetes.io/name: pipelines-app-delivery-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pipelines-app-delivery-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pipelines-app-delivery-backend
    spec:
      serviceAccountName: pipelines-app-delivery
      containers:
        - name: pipelines-app-delivery-http
          image: quay.io/redhat-developer/gitops-backend:v0.0.3
          imagePullPolicy: Always
          env:
          - name: INSECURE
            value: "true"
          volumeMounts:
            - mountPath: "/etc/gitops/ssl"
              name: backend-ssl
              readOnly: true
          ports:
          -  containerPort: 8080
      volumes:
      - name: backend-ssl
        secret:
          secretName: pipelines-app-delivery-backend
