kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-app-delivery
subjects:
- kind: ServiceAccount
  name: pipelines-app-delivery
roleRef:
  kind: Role
  name: pipelines-app-delivery
  apiGroup: rbac.authorization.k8s.io
